import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import Configuration from "../components/Configuration";

const Home: NextPage = () => {
  const [data, setData] = useState();

  useEffect(() => {
    console.log("in useEfect");
    fetch("http://localhost:3001/api/configurations", {
      method: "GET",
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setData(data);
      })
      .catch((err) => console.log(err));
  }, []);

  const postConfig = () => {
    fetch("http://localhost:3001/api/configuration", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: "Newest decrisption",
        description: "Best one ever!",
        color: "red",
      }),
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
      })
      .catch((err) => console.log(err));
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>Hello I am the client</h1>
        {/* display all configurations that came back from server */}
        {data &&
          data?.map((config, i) => {
            return <Configuration key={i} {...config} />;
          })}

        <button onClick={postConfig}>Post Configuration</button>
      </main>
    </>
  );
};

export default Home;
