import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useQuery, useMutation } from 'react-query';
import Configuration from '../components/Configuration';

const Home: NextPage = () => {
  const { isLoading, error, data } = useQuery('configurations', () =>
    fetch('http://localhost:3001/api/configurations').then((res) => res.json())
  );

  const { mutate, isLoading: isMutating } = useMutation(() => {
    return fetch('http://localhost:3001/api/configuration', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: 'Newest decrisption',
        description: 'Best one ever!',
        color: 'red',
      }),
    });
  });

  const postConfig = (e) => {
    e.preventDefault();
    mutate();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center'>
        <h1>Hello I am the client</h1>
        {/* display all configurations that came back from server */}
        {data &&
          data?.map((config, i) => {
            return <Configuration key={i} {...config} />;
          })}

        <button onClick={postConfig}>Post Configuration</button>
      </main>
    </>
  );
};

export default Home;
